import React, { useState } from "react";
import { Loader2Icon, Sparkles } from "lucide-react";

const Home = () => {
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);

  const onSubmitHandler = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    setTimeout(() => setLoading(false), 3000);
  };

  return (
    <section
      className="
        relative min-h-screen px-4 pb-32 overflow-hidden
        bg-gradient-to-b from-slate-50 to-slate-100
        dark:from-[#0B0F1A] dark:to-[#070A13]
        text-slate-900 dark:text-slate-100
        flex flex-col items-center
      "
    >
      {/* AI Blue background glow */}
      <div className="absolute inset-0 pointer-events-none">
        <div className="ai-blue-glow top-24 left-1/2 -translate-x-1/2" />
        <div className="ai-blue-glow-soft bottom-24 right-24" />
      </div>

      {/* Badge */}
      <div className="relative mt-20 flex items-center gap-2 border border-slate-300 dark:border-slate-700 rounded-full p-1 pr-3 text-sm animate-fade-in">
        <span
          className="
  bg-blue-700 dark:bg-blue-600
  text-white text-xs px-3 py-1 rounded-full
"
        >
          AI
        </span>
        Website generation platform
      </div>

      {/* Heading */}
      <h1 className="relative mt-8 text-center text-[42px] md:text-6xl font-bold max-w-4xl leading-tight animate-slide-up">
        AI that builds{" "}
        <span className="bg-clip-text text-transparent bg-gradient-to-r bg-blue-700 dark:bg-blue-600 animate-gradient">
          modern websites
        </span>{" "}
        instantly
      </h1>

      <p className="relative mt-4 text-center max-w-xl text-slate-600 dark:text-slate-400 animate-fade-in delay-150">
        Turn a simple prompt into a production-ready website — layout, UI, and
        structure generated by AI.
      </p>

      {/* Form */}
      <form
        onSubmit={onSubmitHandler}
        className="
          relative mt-12 max-w-2xl w-full rounded-2xl p-5
          bg-white/80 dark:bg-white/5
          border border-slate-300 dark:border-slate-700
          backdrop-blur-xl
          flex flex-col gap-4
          animate-scale-in
        "
      >
        <textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          rows={4}
          placeholder="Describe your website idea (startup, portfolio, SaaS, business site)"
          className="
            bg-transparent resize-none outline-none
            text-slate-800 dark:text-slate-200
            placeholder:text-slate-400
          "
          required
        />

        <button
          type="submit"
          disabled={loading}
          className="
  ml-auto flex items-center gap-2
  bg-gradient-to-r 
  from-blue-700 to-blue-600
  dark:from-blue-600 dark:to-blue-500
  hover:from-blue-600 hover:to-blue-500
  dark:hover:from-blue-500 dark:hover:to-blue-400
  text-white rounded-md px-5 py-2.5
  transition-all duration-300
  shadow-lg hover:shadow-blue-500/30
"
        >
          {!loading ? (
            <>
              <Sparkles className="size-4 animate-pulse" />
              Generate Website
            </>
          ) : (
            <>
              Generating
              <Loader2Icon className="animate-spin size-4" />
            </>
          )}
        </button>
      </form>

      {/* Logos */}
      <div className="relative mt-20 w-full max-w-5xl overflow-hidden mx-auto">
        <div className="flex w-max marquee-ai items-center gap-10">
          {[
            { name: "Framer", logo: "framer" },
            { name: "Huawei", logo: "huawei" },
            { name: "Instagram", logo: "instagram" },
            { name: "Microsoft", logo: "microsoft" },
            { name: "Walmart", logo: "walmart" },
          ]
            .concat([
              { name: "Framer", logo: "framer" },
              { name: "Huawei", logo: "huawei" },
              { name: "Instagram", logo: "instagram" },
              { name: "Microsoft", logo: "microsoft" },
              { name: "Walmart", logo: "walmart" },
            ])
            .map((brand, index) => (
              <div
                key={index}
                className="flex items-center gap-3 opacity-70 hover:opacity-100 transition"
              >
                <img
                  src={`/logos/${brand.logo}.svg`}
                  alt={brand.name}
                  className="h-8 md:h-9 filter dark:invert dark:brightness-90"
                />
                <span className="text-base md:text-lg font-semibold text-slate-600 dark:text-slate-300">
                  {brand.name}
                </span>
              </div>
            ))}
        </div>
      </div>
    </section>
  );
};

export default Home;
